# syntax=docker/dockerfile:1

FROM python:3.11-alpine

WORKDIR /app

RUN apk --no-cache add musl-dev linux-headers g++ gfortran cmake

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "main.py" ]
